### PR TITLE
Fixed bug in documentation

### PR DESCRIPTION
**Pull request by Holicz**

### CODE REVIEW

**Comment by chteuchteu** [comment]
In PHP, lines should end with a semicolon, not with a comma. This is not a bug.

**Comment by Holicz** [comment]
Even if this line is going to array?

**Comment by chteuchteu** [comment]
Please review your commit: in line 67 (the one you edited), we're calling the `addChild` method so we must put a semicolon (`;`) at the end of the row:

    $blog->addChild(new MenuItemModel(/* ... */));

Actually there's an error just 3 lines before:

    $menuItems = array(
        $blog = new MenuItemModel('ItemId', 'ItemDisplayName', 'item_symfony_route', array(/* options */), 'iconclasses fa fa-plane'); // <- HERE
    );

Here, the semicolon should be removed (we can put a comma here but it is optional). Have you made the modification on the wrong line? If so, would you mind creating a pull request for this please?

Thank you!

**Comment by Holicz** [comment]
Oh, missclick :). 

PR created, thank you for the correction.

**Comment by chteuchteu** [comment]
Not a problem, thanks for the PR!

**Pull request closed without merging**
