### PR TITLE
Add flash message support

### PR DESCRIPTION
**Pull request by lucasaba**
The code is not mine. It is an adaptation from [mopa/bootstrap-bundle](https://github.com/phiamo/MopaBootstrapBundle):
[Flash macro](https://github.com/phiamo/MopaBootstrapBundle/blob/master/Resources/views/flash.html.twig)
[Block inclusion](https://github.com/phiamo/MopaBootstrapBundle/blob/master/Resources/views/base.html.twig#L63)

### CODE REVIEW

**Comment by chteuchteu** [comment]
Nice work!
Could you document it please?

Also, shouldn't we use [AdminLTE's callouts](https://almsaeedstudio.com/themes/AdminLTE/pages/UI/general.html)? We could then deduce its class (`callout callout-(danger|info|warning|success)`) from the flashbag: `$this->addFlash('success', 'This action was a success');` would use `callout callout-success`

**Comment by chteuchteu** [comment]
Looping over each bag (success, info, warning or danger) could be done like this:

	{% for bag, messages in app.session.flashbag %}
		{% for message in messages %}
			<div class="callout callout-{{ bag }}">
				{{ message }}
			</div>
		{% endfor %}
	{% endfor %}

**Comment by lucasaba** [comment]
:+1: just a question: why the callout instead of the alert ?

**Comment by lucasaba** [comment]
@chteuchteu looping in this way would not clean the flashbag. With [flasgbag.all](http://api.symfony.com/2.3/Symfony/Component/HttpFoundation/Session/Flash/FlashBag.html#method_all) you get all messages from all bags and clear the messages from the stack.

And with the flash macro, you can use the additiona aruments for the closing function:

```
{{ session_flash(true) }}
```

**Comment by chteuchteu** [comment]
You're right (for both flash macro, didn't see it, and the dismissable alerts)!

**Comment by oidnus** [comment]
Good work i wait for merge.

**Comment by chteuchteu** [comment]
It seems that this PR has been forgotten... Merging!

**Comment by lucasaba** [comment]
Thanks guys :+1:

**Pull request merged**
