### PR TITLE
Fix "ECONFLICT Unable to find suitable version for underscore"

### PR DESCRIPTION
**Pull request by bigben3333**

### CODE REVIEW

**Comment by alinalexandru** [comment]
Why you haven't add the version limit at https://github.com/bigben3333/AdminThemeBundle/blob/patch-1/Resources/bower/bower.json#L23
@avanzu Could you please tag each dependency ?

**Comment by gtrias** [comment]
+1

**Comment by 2ndkauboy** [comment]
+1 for tagging each dependency

This would also fix #42.

**Comment by Dimentar** [comment]
+1

**Comment by avanzu** [comment]
should be addressed by the latest release. Please re-open if necessary.

**Pull request closed without merging**
