### PR TITLE
Extended nav user widget

### PR DESCRIPTION
**Pull request by fr05t1k**
- feature: adding links into widget
- feature: disabling logout and profile links

### CODE REVIEW

**Comment by shakaran** [comment]
@chteuchteu this PR looks clean to me as nice as feature, but probably you want to check fine all the details before to merge. It has clean merge too. Thanks

**Comment by chteuchteu** [comment]
@shakaran This needs a bit more digging and testing indeed :/

**Comment by shakaran** [comment]
@fr05t1k checked and merged to master. Thanks for your contribution!

**Comment by fr05t1k** [comment]
It took more than a year 😄

**Comment by shakaran** [comment]
@fr05t1k yes, sorry for that, the original author doesn't have enough time. I take the seat as collaborator. I will try to speed up the things here ;)

**Pull request merged**
