### PR TITLE
Fix dependency bugs

### PR DESCRIPTION
**Pull request by jibundeyare**
Constrain underscore.js to 1.x.x in bower.json
Updated adminlte bootstrap-wysihtml5 plugin assets list

### CODE REVIEW

**Comment by Halleck45** [comment]
:+1: 

today I cannot use this Bundle due to #46

**Comment by bpolaszek** [comment]
Same here.

**Comment by palra** [comment]
Exactly the same here :+1:

**Comment by ogerik** [comment]
Please merge

**Comment by avanzu** [comment]
see #41

**Pull request closed without merging**
