### PR TITLE
Sidebar navigation labels support

### PR DESCRIPTION
**Pull request by surivrox**
No backward incompatibilities. Example usage:

```php
<?php
namespace MyAdminBundle\EventListener;

// ...

use Avanzu\AdminThemeBundle\Model\MenuItemModel;
use Symfony\Component\HttpFoundation\Request;

class MyMenuItemListListener {

    // ...

    protected function getMenu(Request $request) {
        return array(
			new MenuItemModel('label', 'Label', false),
		);
    }

    // ...

}
```

### CODE REVIEW

**Comment by surivrox** [comment]
Any feedback on this pull request?

**Comment by chteuchteu** [comment]
Thanks for the reminder!

Could you update the documentation to include your usage example please? I think that other users would be interested in this feature, but it should be documented first.

I think we'll be safe to merge this PR once it'll be done.

Thank you!

**Comment by surivrox** [comment]
Updated.

**Comment by chteuchteu** [comment]
Thanks!
Merged.

**Comment by OskarStark** [comment]
:+1:

**Pull request merged**
