### PR TITLE
Update static resources for prod (based on files from the dev)

### PR DESCRIPTION
**Pull request by surivrox**
The fix for https://github.com/avanzu/AdminThemeBundle/issues/65

### CODE REVIEW

**Comment by chteuchteu** [comment]
Are you sure about this pull request? There seems to be unnecessary modifications, please check your commit

**Comment by chteuchteu** [comment]
Could you explain the other files changes please?
Have you replaced prod static resources with dev ones?

**Comment by surivrox** [comment]
Yes, I replaced prod static resources with the dev ones. It looks that prod is a bit outdated:
Bootstrap v3.2.0 vs Bootstrap v3.3.5
Ionicons, v1.5.2 vs v2.0.0
AdminLTE v2.0. vs v2.3.0
etc. and i thought that it's a good occasion to update it.

**Comment by chteuchteu** [comment]
Yes it is indeed!
I'm quite surprised that we didn't updated it earlier. Shouldn't prod contain the same files as dev?
Please let me ask @avanzu for confirmation before merging and closing #66.

**Comment by OskarStark** [comment]
> Shouldn't prod contain the same files as dev?

IMO yes

**Comment by avanzu** [comment]
prod should indeed contain the same code as dev when tested and ready. 

Since the "static" assets for dev and/or prod are also generated as [described here](https://github.com/avanzu/AdminThemeBundle/blob/master/Resources/docs/rebuild.md) the general idea is to first build the static dev assets, checking for issues and then building the prod assets. 
 
Apparently we have divergent dev and prod "static" assets, right?

**Comment by chteuchteu** [comment]
There was indeed a difference between dev's FontAwesome version and prod's one.
This can lead to awkward situations where icons where showing up in dev environment, but not in production.

**Pull request merged**
