### PR TITLE
Remove backbone dependence

### PR DESCRIPTION
**Pull request by Big-Shark**

### CODE REVIEW

**Comment by OskarStark** [comment]
Can you please explain, WHY we should remove this?

**Comment by Big-Shark** [comment]
@OskarStark because AdminLTE doe's not use backbone by default, and we don't need add it by default

**Comment by numerogeek** [comment]
That would be great to merge it as Backbone is the source of a bug here.

**Comment by chteuchteu** [comment]
@OskarStark, what do you think?

**Comment by shakaran** [comment]
I am temptative merging this PR since I don't see backbone as real dependency. If someone see weird behaviour or bug, please reopen to revert

**Pull request merged**
